dist: xenial
sudo: required
language: rust
rust:
  - nightly
  - beta
  - stable
env:
  global:
    - DATABASE_URL=mysql://root:password@127.0.0.1:3306/mysql
before_install:
  - sudo bash -c "echo '[mysqld]' >> /usr/share/mysql/my-default.cnf"
  - sudo bash -c "echo 'sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES' >> /usr/share/mysql/my-default.cnf"
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('password') where User='root'; FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root -ppassword
  - sudo service mysql restart
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustup component add rustfmt
script:
  - cargo test
  - cargo test --features ssl
  - cargo fmt -- --check

