[package]
authors = ["blackbeam <aikorsky@gmail.com>"]
description = "Tokio based asynchronous MySql client library."
documentation = "http://blackbeam.org/mysql_async/mysql_async/"
keywords = ["mysql", "database", "asynchronous", "async"]
license = "MIT/Apache-2.0"
name = "mysql_async"
readme = "README.md"
repository = "https://github.com/blackbeam/mysql_async"
version = "0.5.0"

[dependencies]
bitflags = "~0.7"
byteorder = "~1.0.0"
chrono = "~0.2"
either = "~1.0.0"
error-chain = "~0.7.1"
fnv = "~1.0"
futures = "~0.1.1"
lazy_static = "~0.2.1"
log = "~0.3.6"
rustc-serialize = "~0.3.22"
sha1 = "~0.2.0"
time = "~0.1"
tokio-core = "~0.1.1"
twox-hash = "~1.0.0"
url = "^1.2.1"

[dependencies.regex]
default-features = false
version = "~0.2.1"

[dev-dependencies]
env_logger = "~0.4.0"

[features]
nightly = []

[lib]
name = "mysql_async"
path = "src/lib.rs"
