[package]
authors = ["blackbeam <aikorsky@gmail.com>"]
description = "Tokio based asynchronous MySql client library."
documentation = "http://blackbeam.org/mysql_async/mysql_async/"
keywords = ["mysql", "database", "asynchronous", "async"]
license = "MIT/Apache-2.0"
name = "mysql_async"
readme = "README.md"
repository = "https://github.com/blackbeam/mysql_async"
version = "0.11.1"

[dependencies]
bitflags = "0.9"
byteorder = "1"
chrono = "0.4"
error-chain = "0.10"
fnv = "1"
futures = "0.1"
lazy_static = "0.2"
mio = "0.6"
native-tls = { version = "0.1", optional = true }
serde = "1"
serde_json = "1"
sha1 = "0.2"
time = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
tokio-tls = { version = "0.1", optional = true }
twox-hash = "1"
url = "1"

[dependencies.regex]
default-features = false
version = "0.2"

[features]
nightly = []
ssl = ['native-tls', 'tokio-tls']

[lib]
name = "mysql_async"
path = "src/lib.rs"
