[package]
name = "mysql_async"
version = "0.1.0"
authors = ["blackbeam <aikorsky@gmail.com>"]
license = "MIT/Apache-2.0"

[lib]
name = "mysql_async"
path = "src/lib.rs"

[dependencies]
bitflags = "~0.7"
byteorder = "~0.5.3"
chrono = "~0.2"
error-chain = "~0.5.0"
fnv = "~1.0"
futures = "~0.1.1"
lazy_static = "~0.2.1"
log = "~0.3.6"
sha1 = "~0.2.0"
time = "~0.1"
tokio-core = "~0.1.0"
url = "^1.2.1"
either = "~1.0.0"

[dependencies.regex]
version = "~0.1"
default-features = false

[dev-dependencies]
env_logger = "~0.3.5"

[features]
nightly = []
